### ISSUE TITLE
valid_validator_sig_transacitons

### ISSUE THREAD

**Issue by Hongchenglong** [hanglearning/VBFL#10]
I find a bug in `main.py`, there are two `valid_validator_sig_transacitons` in line 690. 

I think maybe one of them should be `invalid_validator_sig_transacitons`.

**Comment by hanglearning** [comment]
Thank you for the bug report again, Hongchenglong! Yes, that's indeed wrong, and it's most likely should be `invalid_validator_sig_transacitons`. I actually never simulated any transactions having invalid signatures so I guess that's how I missed it. Sorry for the confusion.

Do you prefer to create a PR or let me change and push? Please let me know, thanks!

**Comment by Hongchenglong** [comment]
Sure, this is my PR #11.

**Comment by hanglearning** [comment]
Thanks for keeping the VBFL codebase improved, @Hongchenglong!
