### ISSUE TITLE
Question about a few details

### ISSUE THREAD

**Issue by realcly** [hanglearning/VBFL#3]
Thank you for your sharing!  After reading your paper and code, I would like to ask you a few details and hope to get your reply.  

1. As shown in the figure below, this is a paragraph from your article.  In your VBFL design, does every device have a complete blockchain?  

![image](https://user-images.githubusercontent.com/59962243/178138239-8dd4b38f-f5cf-45ea-8179-cefde4dc1dbb.png)

2. If it is a Non-IID method, the data distribution of the validator is different from that of the associated worker, is the verification result of the validator reasonable?  

Thanks for your answer!

**Comment by hanglearning** [comment]
Hi realcly, thanks for your interest in our work! Here are my answers to your questions -

1. Yes, each device has a complete blockchain, that's also why we test for forking events, which are shown later in the paper. This [video](https://www.youtube.com/watch?v=LMseEXEITvw&t=4510s&ab_channel=HangChen) is my talk about VBFL, in which it shows the details of possible forking events.

2. This is a great question! I later have this question myself as well. When I wrote the VBFL code, I adopted the FL method from another repo which has the option to turn on/off the iid dataset distribution. I turned it on and assumed that the whole dataset was sharded in a non-iid way. I should have tested how non-iid the datasets among each device are, such as using the method in this [paper](https://arxiv.org/pdf/1909.06335.pdf). So to answer your question, I believe if the datasets of the validator and its associated worker are very non-iid, this validation method is not reasonable and would fail. Therefore, the datasets among each device from my experiments may be treated as iid, and I admit this is a problem of this paper.

I am now doing another work based on VBFL that takes non-iidness into account. I will share it with you once I am done if you are interested. By the way, are you a fan of Jay Chou? I am a big fan! Can't wait for July 15th!

**Comment by realcly** [comment]
> 

Thanks for your answer and sharing!  I am also very interested in your other work and hope to learn and communicate with you!  Yes, I'm a super super loyal Jay Chou fan and I can't wait for July 15th too! Greatest Works of Art !

**Comment by hanglearning** [comment]
WOW!!! ME TOO!!! Super loyal fan since 八度空間！We should absolutely keep in touch! I will update you here once I publish my new work. I have every of his album, in double! One for collection (never open) and one to enjoy. Greatest Works of Art!!!

**Comment by realcly** [comment]
> WOW!!! ME TOO!!! Super loyal fan since 八度空間！We should absolutely keep in touch! I will update you here once I publish my new work. I have every of his album, in double! One for collection (never open) and one to enjoy. Greatest Works of Art!!!

It's such a pleasure to meet you, what a wonderful fate!  I have been a Jay Chou fan for 10 years since junior high school!  Looking forward to your new works, just like the works of our common idol Jay Chou!  Thanks!

**Comment by hanglearning** [comment]
> It's such a pleasure to meet you, what a wonderful fate! I have been a Jay Chou fan for 10 years since junior high school! Looking forward to your new works, just like the works of our common idol Jay Chou! Thanks!

Me too me too! Although we all know that Jay Chou's influence is huge, I never imagine that I could meet another Jay Chou's super fan on GitHub! Jay is truly a universal figure 🎼 Thank you and absolutely! Let's produce great works and become the Jay Chou of the tech world!

**Comment by realcly** [comment]
> > It's such a pleasure to meet you, what a wonderful fate! I have been a Jay Chou fan for 10 years since junior high school! Looking forward to your new works, just like the works of our common idol Jay Chou! Thanks!
> 
> Me too me too! Although we all know that Jay Chou's influence is huge, I never imagine that I could meet another Jay Chou's super fan on GitHub! Jay is truly a universal figure 🎼 Thank you and absolutely! Let's produce great works and become the Jay Chou of the tech world!

Thank you, let us work tirelessly towards this goal together!
