### ISSUE TITLE
NotADirectoryError

### ISSUE THREAD

**Issue by Hongchenglong** [hanglearning/VBFL#6]
I cannot run the code `f3_device_overall_learning_curve_VFL.py`, the error as fowllowing: 
```
NotADirectoryError: [Errno 20] Not a directory: 'VBFL/plotting_logs/VFL_nm0/run1/comm_1.txt/client_1_local_comm_1.txt.txt'
```
I guess, there are some files missing. But I cannot find the corresponding log file.

**Comment by hanglearning** [comment]
Hi Hongchenglong, I am sorry for my messy code as I was a rookie coder at that time, and probably still one haha.

It's been almost two years and I apologize I forgot some details. Please help me reproduce the issue -

The path you provided `VBFL/plotting_logs/VFL_nm0/run1/comm_1.txt/client_1_local_comm_1.txt.txt` definitely looks incorrect. I believe the correct path of the log file would be `VBFL/plotting_logs/VFL_nm0/run1/comm_1/client_1_local_comm_1.txt`. I assume you have run the vanilla FL experiment whose code resides in `WHDY_vanilla_malicious_involved_fedavg`, then

1. Could you first check if file `VBFL/plotting_logs/VFL_nm0/run1/comm_1/client_1_local_comm_1.txt` exists?
2. If so, could you let me know what is the argument you provided to the program? Namely, the `log_folder` variable.

Thanks!

**Comment by Hongchenglong** [comment]
Hi @hanglearning, 
1. the file `file VBFL/plotting_logs/VFL_nm0/run1/comm_1/client_1_local_comm_1.txt exists` don't exists. 
2. The parameter I provided to the program is 
```
{
	"name": "f3_device_overall_learning_curve_VFL.py",
	"type": "python",
	"request": "launch",
	"program": "${workspaceFolder}/plottings/f3_device_overall_learning_curve_VFL.py",
	"console": "integratedTerminal",
	"args": ["${workspaceFolder}/plotting_logs/VFL_nm0/run1"]
}
```
and the parameter is come from your file `launch.json`.

Thanks!

**Comment by hanglearning** [comment]
Hi Hongchenglong, thanks for providing the details!

To plot our simulation results, please follow these steps -

1. Download [plotting_logs.zip](https://github.com/hanglearning/VBFL/blob/master/plotting_logs.zip)
2. Unzip it and put the folder `plotting_logs` under the VBFL root
3. Try running `f3_device_overall_learning_curve_VFL.py` again
4. If plotting still fails, please give the absolute path to the log folder, e.g., `/Users/<your_username>/VBFL/plotting_logs/VFL_nm0/run1`

To plot your own simulation, please direct the program to your running log folder after executing `main.py`.

Please let me know if this works. Thank you!

**Comment by Hongchenglong** [comment]
Hi @hanglearning, thanks for your reply!
It doesn't work. 
1. I redownload and unzip `plotting_logs.zip`, but there is no such file `VBFL/plotting_logs/VFL_nm0/run1/comm_1`.
2. I executed `main.py`, but it also did not generate the folder `comm_1`.

Finally, I found what files `f3_device_overall_learning_curve_VFL` need. 
So I execute 
```
{
	"name": "server.py",
	"type": "python",
	"request": "launch",
	"program": "${workspaceFolder}/WHDY_vanilla_malicious_involved_fedavg/server.py",
	"console": "integratedTerminal",
	"args": ["-nc", "3", "-mn", "mnist_cnn", "-iid", "0", "-nm", "0"]
}
```
it generate the folder `/WHDY_vanilla_malicious_involved_fedavg/logs/11232022_142338`, and I execute
```
{
	"name": "f3_device_overall_learning_curve_VFL.py",
	"type": "python",
	"request": "launch",
	"program": "${workspaceFolder}/plottings/f3_device_overall_learning_curve_VFL.py",
	"console": "integratedTerminal",
	"args": ["${workspaceFolder}/WHDY_vanilla_malicious_involved_fedavg/logs/11232022_142338"]
}
``` 
Then it's finally plot successfully!!!

Thank you for your patient answer, and I am sorry for my poor english.

**Comment by hanglearning** [comment]
Oh! My bad, yes, this plots the vanilla FL's learning curves. The correct code to execute is inside of `WHDY_vanilla_malicious_involved_fedavg`, not `main.py`. 

I am glad that it now works! Thanks for providing the instructions 👍 No worries, your English is perfectly understandable!
